import { ClientOnly } from "@tanstack/react-router";
import { useSuspenseQuery } from "@tanstack/react-query";
import { lazy, Suspense, useCallback } from "react";
import { AlertTriangle, ArrowRight, CheckCircle2, Database, Eye, Gauge, RadioTower, ShieldAlert } from "lucide-react";
import { blendQuery, leadTimesQuery, regionsQuery, variablesQuery } from "@/features/data/queries";
import type { RegionCode, VariableName } from "@/features/data/types";
import { SelectControl } from "@/features/shared/Controls";
import { DataStatus } from "@/features/shared/DataStatus";
import { TopBar } from "@/features/shared/AppShell";
import { Meter, Metric } from "@/features/shared/Metric";
const RegionMap=lazy(()=>import("./RegionMap"));
function pct(n:number){return `${Math.round(n*100)}%`}
export function ForecastView({region,variable,lead,onRegion,onVariable,onLead}:{region:RegionCode;variable:VariableName;lead:number;onRegion:(v:RegionCode)=>void;onVariable:(v:VariableName)=>void;onLead:(v:number)=>void}){
 const {data:regions}=useSuspenseQuery(regionsQuery); const {data:variables}=useSuspenseQuery(variablesQuery); const {data:leads}=useSuspenseQuery(leadTimesQuery); const {data:result}=useSuspenseQuery(blendQuery(region,variable,lead)); const d=result.data;
 const mapSelect=useCallback((v:RegionCode)=>onRegion(v),[onRegion]);
 return <><TopBar mode={result.mode}/><div className="control-deck"><SelectControl label="Pilot region" value={region} onChange={v=>onRegion(v as RegionCode)} options={regions.data.map(r=>({value:r.code,label:`${r.code} · ${r.name}`}))}/><SelectControl label="Forecast variable" value={variable} onChange={v=>onVariable(v as VariableName)} options={variables.data.map(v=>({value:v.variable,label:v.variable.replace("_"," ")}))}/><SelectControl label="Lead time" value={String(lead)} onChange={v=>onLead(Number(v))} options={leads.data.map(l=>({value:String(l),label:`+${l} hours`}))}/><DataStatus mode={result.mode}/></div>
 <div className="forecast-grid"><section className="map-panel panel"><div className="panel-head"><div><span className="kicker">PILOT ZONE</span><h2>{d.region_name}</h2></div><span className="coordinate">{regions.data.find(r=>r.code===region)?.lat}°N · {regions.data.find(r=>r.code===region)?.lon}°E</span></div><ClientOnly fallback={<div className="map-skeleton"/>}><Suspense fallback={<div className="map-skeleton"/>}><RegionMap regions={regions.data} selected={region} onSelect={mapSelect}/></Suspense></ClientOnly><div className="map-legend">{regions.data.map(r=><button key={r.code} onClick={()=>onRegion(r.code)} className={r.code===region?"active":""}><i/>{r.code}</button>)}</div></section>
 <section className={`forecast-readout panel ${d.abstain?"abstain":""}`}><div className="panel-head"><div><span className="kicker">BLENDED OUTPUT</span><h2>{d.abstain?"Human review advised":"Forecast cleared"}</h2></div>{d.abstain?<ShieldAlert/>:<CheckCircle2/>}</div><div className="final-value"><strong>{d.final_value.toFixed(1)}</strong><span>{d.unit}</span></div><div className="forecast-pipeline"><div><small>RAW BLEND</small><b>{d.raw_blend_value.toFixed(2)}</b></div><ArrowRight/><div><small>BIAS CORRECTED</small><b>{d.bias_corrected_value.toFixed(2)}</b></div><ArrowRight/><div><small>FINAL</small><b>{d.final_value.toFixed(2)}</b></div></div><div className="decision-strip"><span><RadioTower/>+{d.lead_hours}H</span><span><Gauge/>{d.regime.replaceAll("_"," ")}</span><span><AlertTriangle/>{pct(d.bust_probability)} bust risk</span></div>{d.abstain&&<div className="abstain-note">Low confidence · preserve the numeric output for context, but escalate operational use to a forecaster.</div>}</section>
 <section className="source-panel panel"><div className="panel-head"><div><span className="kicker">SOURCE ATTRIBUTION</span><h2>Models in the blend</h2></div><span className="micro-copy">Weight · value · historical skill</span></div><div className="source-list">{d.sources.map(s=><div className={`source-row ${(s.weight??0)===0?"excluded":""}`} key={s.model}><div className="source-name"><i className={`signal-${s.model.toLowerCase()}`}/><b>{s.model}</b>{s.weight===0&&<span>EXCLUDED</span>}</div><div className="source-bar"><i style={{transform:`scaleX(${s.weight??0})`}}/></div><strong>{pct(s.weight??0)}</strong><span>{s.forecast_value.toFixed(1)} {d.unit}</span><span>skill {(s.historical_skill??0).toFixed(3)}</span></div>)}</div></section>
 <section className="trust-panel panel"><div className="panel-head"><div><span className="kicker">TRUST COMPOSITION</span><h2>Five signals, one decision</h2></div><div className="trust-orbit"><strong>{pct(d.trust.trust_score)}</strong><span>TRUST</span></div></div><div className="trust-grid">{Object.entries(d.trust).filter(([k])=>k!=="trust_score").map(([k,v])=><Meter key={k} value={v*100} tone={v<.35?"warning":"primary"} label={k.replace("_component","").replaceAll("_"," ")}/>)}</div></section>
 <section className="regime-panel panel"><div className="panel-head"><div><span className="kicker">REGIME CLASSIFIER</span><h2>{d.regime.replaceAll("_"," ")}</h2></div><Eye/></div><div className="prob-bars">{Object.entries(d.regime_probs).sort((a,b)=>b[1]-a[1]).map(([name,val])=><Meter key={name} value={val*100} tone={name===d.regime?"primary":"honest"} label={name.replaceAll("_"," ")}/>)}</div></section>
 <section className="explain-panel panel"><div className="panel-head"><div><span className="kicker">EXPLANATION BACKEND</span><h2>Why this blend?</h2></div><span className="micro-copy">Signed contribution</span></div><div className="explanation-list">{d.explanation.map(x=><div key={x.feature}><div className="explain-row"><b>{x.feature.replaceAll("_"," ")}</b><span className={x.contribution>=0?"positive":"negative"}>{x.contribution>=0?"+":""}{x.contribution.toFixed(3)}</span></div><div className="contribution-track"><i className={x.contribution>=0?"positive":"negative"} style={{width:`${Math.min(50,Math.abs(x.contribution)*220)}%`}}/></div><p>{x.detail}</p></div>)}</div></section></div>
 <footer className="provenance"><Database/><span>PROVENANCE</span>{Object.entries(d.provenance).map(([k,v])=><span key={k}><b>{k}</b> {v}</span>)}</footer></>;
}
