"""
Central orchestrator: wires ingestion -> regime -> skill -> blend -> bias
correction -> calibration -> trust/bust -> explanation -> narrative into one
call, exactly following the Operational Data Flow in Section 14 / Figure 3.
Used identically by the live /forecast/blend route, the replay precompute
script, and the counterfactual "weight lab" route, so all three can never
drift apart.

Two behavioural fixes vs. the earlier version:

1. Regime probabilities are now generated by the REAL context engine
   (app/regime_detector.py) from the actual multi-variable forecast medians
   available at this context, rather than only reading the pre-baked
   synthetic regime_probs the generator happened to stash on the row. The
   synthetic regime_probs are kept only as a fallback for contexts where the
   other two variables aren't cached (preserves synthetic-data
   compatibility).
2. "historical_skill" and "climatological_anomaly" are read directly off
   each ForecastRow's precomputed, leakage-free expanding columns
   (see app/data_prep.py) instead of a live DB lookup against a table that
   could include future/test-period outcomes.
"""
from __future__ import annotations
import numpy as np
from datetime import datetime
from sqlalchemy.orm import Session

from app.config import PILOT_ZONES, MODELS, REGIMES
from app.models_db import ForecastRow
from app.skill_engine import lookup_historical_skill
from app.regime_detector import detect_regime
from app.blending.blend import compute_weights, blend_forecast
from app.blending.calibration import apply_quantile_map, exceedance_probabilities
from app.blending.trust import compute_trust
from app.blending.explain import _shap_top_drivers, generate_narrative
from app.blending.analogue import find_analogues
from app.blending.features import encode
from app.schemas import ForecastRecord, WeightExplanation, BlendedForecastResponse


def _detect_regime_from_context(db: Session, region: str, valid_time: datetime, lead_hours: int,
                                 season: str, fallback_probs: dict, lat: float) -> dict:
    """Pulls the OTHER variables' cached rows for this exact context and feeds
    their (multi-model median) values into the real rule-based regime
    detector. Falls back to the synthetic-generator's own noisy regime_probs
    only when the other variables aren't available for this context."""
    other_rows = (
        db.query(ForecastRow.variable, ForecastRow.forecast_value)
        .filter(ForecastRow.region == region, ForecastRow.valid_time == valid_time,
                ForecastRow.lead_hours == lead_hours)
        .all()
    )
    if not other_rows:
        return fallback_probs

    import pandas as pd
    df = pd.DataFrame(other_rows, columns=["variable", "forecast_value"])
    medians = df.groupby("variable")["forecast_value"].median().to_dict()
    if not medians:
        return fallback_probs
    return detect_regime(medians, season, lat)


def run_blend_pipeline(
    db: Session, region: str, variable: str, valid_time: datetime, lead_hours: int,
    regime_override: str | None = None,
) -> BlendedForecastResponse:
    rows = (
        db.query(ForecastRow)
        .filter(ForecastRow.region == region, ForecastRow.variable == variable,
                ForecastRow.valid_time == valid_time, ForecastRow.lead_hours == lead_hours)
        .all()
    )
    if not rows:
        raise ValueError("No cached forecast sources for that region/variable/valid_time/lead_hours.")

    season = rows[0].season
    lat = float(np.mean(PILOT_ZONES[region]["lat_range"]))
    synthetic_regime_probs = rows[0].regime_probs or {}

    if regime_override:
        # Counterfactual weight lab: actually perturb the context the
        # meta-model sees (not just the label) so weights genuinely respond.
        regime_probs = {r: (0.85 if r == regime_override else 0.15 / (len(REGIMES) - 1)) for r in REGIMES}
        regime = regime_override
    else:
        regime_probs = _detect_regime_from_context(
            db, region, valid_time, lead_hours, season, synthetic_regime_probs, lat
        )
        regime = max(regime_probs, key=regime_probs.get) if regime_probs else rows[0].regime

    forecast_values = {r.model: r.forecast_value for r in rows}
    disagreement = float(np.std(list(forecast_values.values())))
    mean_val = float(np.mean(list(forecast_values.values())))
    value_scale = {"precipitation": 100.0, "temperature": 8.0, "wind_speed": 40.0}.get(variable, 50.0)

    # Leakage-free, per-row expanding features precomputed in app/data_prep.py.
    # Fall back to the frozen (train+val only) static lookup for any row that
    # somehow has no expanding value cached (should not happen for archived
    # data, but keeps this robust for ad-hoc contexts).
    historical_skill_by_model = {}
    climatological_anomaly_by_model = {}
    for r in rows:
        historical_skill_by_model[r.model] = (
            r.historical_skill_expanding if r.historical_skill_expanding is not None
            else lookup_historical_skill(db, r.model, region, lead_hours, season, variable)
        )
        climatological_anomaly_by_model[r.model] = r.climatological_anomaly_norm or 0.0

    weights, weight_source = compute_weights(
        variable=variable, lead_hours=lead_hours, regime_probs=regime_probs, region=region,
        season=season, historical_skill_by_model=historical_skill_by_model,
        disagreement=disagreement, forecast_values=forecast_values,
        climatological_anomaly_by_model=climatological_anomaly_by_model,
    )

    blended_raw = blend_forecast(weights, forecast_values)
    blended_calibrated = apply_quantile_map(blended_raw, variable, region=region)
    exceed_probs = exceedance_probabilities(blended_calibrated, variable, region=region)

    # context feature vector for the bust classifier (uses blended value as "this model's forecast")
    ctx_feat = encode(
        lead_hours=lead_hours, regime_probs=regime_probs, region=region, season=season,
        historical_skill=float(np.mean(list(historical_skill_by_model.values()))),
        disagreement=disagreement, forecast_value=blended_raw,
        consensus_deviation=0.0,  # the blend itself IS the consensus
        climatological_anomaly=float(np.mean(list(climatological_anomaly_by_model.values()))),
    )

    trust = compute_trust(
        variable=variable, weights=weights, historical_skill_by_model=historical_skill_by_model,
        disagreement=disagreement, lead_hours=lead_hours, regime_probs=regime_probs,
        n_sources_available=len(forecast_values), n_sources_expected=len(MODELS),
        context_features=ctx_feat,
    )

    weight_explanations = []
    for m, w in weights.items():
        consensus_dev = (forecast_values[m] - mean_val) / value_scale
        feat = encode(
            lead_hours=lead_hours, regime_probs=regime_probs, region=region, season=season,
            historical_skill=historical_skill_by_model.get(m, 0.5), disagreement=disagreement,
            forecast_value=forecast_values[m], consensus_deviation=consensus_dev,
            climatological_anomaly=climatological_anomaly_by_model.get(m, 0.0),
        )
        drivers = _shap_top_drivers(variable, m, feat) if weight_source == "meta_model" else []
        weight_explanations.append(WeightExplanation(model=m, weight=w, top_drivers=drivers))

    region_label = PILOT_ZONES[region]["label"]
    narrative = generate_narrative(
        region_label=region_label, variable=variable, valid_time_str=valid_time.isoformat(),
        regime=regime, weights=[w.model_dump() for w in weight_explanations],
        blended_value=blended_calibrated, trust_score=trust["trust_score"],
        disagreement=trust["disagreement"], bust_probability=trust["bust_probability"],
        abstain=trust["abstain"],
    )

    # Analogues must themselves be genuinely "historical" relative to this
    # query -> restrict to strictly earlier valid_times (avoids showing a
    # test-period neighbour as if it were past precedent for another
    # test-period query).
    analogues = find_analogues(db, region, variable, regime, season, lead_hours, before=valid_time)

    raw_sources = [
        ForecastRecord(
            model=r.model, run_time=r.run_time, valid_time=r.valid_time, lead_hours=r.lead_hours,
            variable=r.variable, lat=r.lat, lon=r.lon, forecast_value=r.forecast_value,
            regime_probs=regime_probs, historical_skill=historical_skill_by_model.get(r.model),
            model_weight=weights.get(r.model), trust_score=trust["trust_score"],
            bust_probability=trust["bust_probability"],
        )
        for r in rows
    ]

    return BlendedForecastResponse(
        region=region, variable=variable, valid_time=valid_time, lead_hours=lead_hours,
        regime=regime, regime_probs=regime_probs, raw_sources=raw_sources,
        weights=weight_explanations, blended_value_raw=round(blended_raw, 2),
        blended_value_calibrated=round(blended_calibrated, 2),
        exceedance_probabilities=exceed_probs, trust_score=trust["trust_score"],
        disagreement=trust["disagreement"], bust_probability=trust["bust_probability"],
        abstain=trust["abstain"], narrative=narrative, analogues=analogues,
    )
